### ISSUE TITLE
Missing years in meta_data7.csv

### ISSUE THREAD

**Issue by perwin** [matthewfdaniels/scripts#4]
In making some plots about the time distribution of the movies, I noticed that two entries were missing years:
7972,"tt0460681","Supernatural","","",757665666777777777777777774355677776577526777775677773
and
4633,"tt0244353","The Mists of Avalon","","","003342246454647457200"

"Supernatural" (IMDB id tt0460681) is a TV series, not a movie -- should that perhaps not be in the list, if the list is meant to be movies?
"Mists of Avalon" is a (TV) movie from 2001, according to IMDB.

**Comment by matthewfdaniels** [comment]
You're right. I'm going to pull Supernatural and Mists of Avalon from the dataset. Should not be in there.

Note that I'm adding films as we remove them. Last update had us at 2,005 I believe, so this will us back down to 2,003.

**Comment by perwin** [comment]
Glad to help (in whatever minimal way)! (It's a very interesting project, and it's great that you're making the data available like this.)
