### ISSUE TITLE
Not sure how you get character age

### ISSUE THREAD

**Issue by pssguy** [matthewfdaniels/scripts#5]
in the character_list5 file you give the age of the character, which i assumed came from the year of release and birthdate of actor. I can see how you obtain year of release as there is a common field, script_id with meta-data7, but there does not appear to be the field actor_imdb_id which could be linked to the actor_list.csv
What am I missing here?

**Comment by matthewfdaniels** [comment]
Sorry in the actor list csv there should be birthday.

**Comment by pssguy** [comment]
There is. But I cannot see the common field between actor_list and character_list5 that would enable you to calculate age.
Great resource BTW

**Comment by matthewfdaniels** [comment]
Doh! I'll add this field to the character_list csv in the next update

**Comment by pssguy** [comment]
Thanks. I see you have it new file. 
Sorry to be a pain but any chance you could extend the actor_list to cover all your data? I'm assuming it must be much greater to calculate all these ages. For instance 'Knocked Up' has all the characters ages but of the 18 characters with 100+ words only the 16th, Adam Scott, appears to be in the actors dataset. The stars like Seth Rogan and Katherine Heigl don't figure

**Comment by matthewfdaniels** [comment]
I'm an idiot and didn't do a full export – only the first 5,000 rows. Updating now.
